### ISSUE TITLE
Github Actions: run tests on push

### ISSUE THREAD

**Issue by dominicnzl** [dominicnzl/DriveDok#102]
e.g.
```
name: Java CI with Maven

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
```
